### ISSUE TITLE
Add config option to change draw priority.

### ISSUE THREAD

**Issue by zeakzz** [neilrush/Player-Outline#1]
Im not sure if you could fix this but my true tiles are showing the player outline and it looks kinda bad so if you could fix it that would make this a 10/10 plugin

**Comment by neilrush** [comment]
Could you post a screenshot of what you mentioned?

**Comment by zeakzz** [comment]
sure
![Annotation 2021-12-26 214810](https://user-images.githubusercontent.com/63619162/147438872-6ca5f221-cd50-4b56-a2e0-59af18017ba6.png)
![Annotation 2021-12-26 214953](https://user-images.githubusercontent.com/63619162/147438911-beaadae3-5393-460b-9af6-5e0f2d88d050.png)
.

**Comment by neilrush** [comment]
This is working as intended. 

The outline is always present but just not very noticeable against the contrast of the player and most backgrounds. Afaik there is no way to selectively draw an outline when something is occluded, using RuneLite's libraries. I hope that explains what is going on. If you change the outline color to something more obvious like red you can see what is happening. 

I could add the ability to change the priority of the outline. Then you could set it to draw under your tile markers if it is bothersome.

**Comment by zeakzz** [comment]
that could be cool, if its not too much work

**Comment by neilrush** [comment]
I did some experimentation, and this may not be fixable. I thought this would be easy but, even if the overlay is drawn underneath, the tile marker still blends with the colors of the outline. 😔

![image](https://user-images.githubusercontent.com/31221793/147442968-773720bb-f285-4b05-a3ce-50ab39597051.png)
